budgetproject/budgetproject/budget/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.project_list, name ='list'),
    path('add', views.ProjectCreateView.as_view(), name='add'),
    path('<slug:project_slug>', views.project_detail, name = 'detail'),
]

budgetproject/budgetproject/budgetproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('', include('budget.urls')),
    path('admin/', admin.site.urls),
]

budgetproject/budgetproject/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

budgetproject/budgetproject/budget/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.conf import settings
import json


class Project(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True, blank=True)
    budget = models.DecimalField(max_digits=8, decimal_places=2)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Project, self).save(*args, **kwargs)

    def budget_left(self):
        expense_list = Expense.objects.filter(project=self)
        total_expense_amount = 0
        for expense in expense_list:
            total_expense_amount += expense.amount
        return self.budget - total_expense_amount

    def budget_percentage(self):
        expense_list = Expense.objects.filter(project=self)
        total_expense_amount = 0
        for expense in expense_list:
            total_expense_amount += expense.amount
        return (total_expense_amount/self.budget)*100

    def total_transactions(self):
        expense_list = Expense.objects.filter(project=self)
        return len(expense_list)


class Category(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)




class Expense(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='expenses')
    title = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-amount',)

budgetproject/budgetproject/users/models.py
from django.db import models

# Create your models here.

budgetproject/budgetproject/budget/forms.py
from django import forms

class ExpenseForm(forms.Form):
    title = forms.CharField()
    amount = forms.IntegerField()
    category = forms.CharField()
 

budgetproject/budgetproject/budget/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from .models import Project, Category, Expense
from django.views.generic import CreateView
from django.utils.text import slugify
from .forms import ExpenseForm
from django.contrib.auth.models import User
import json


def project_list(request):
    if request.user.is_authenticated:
        project_list = Project.objects.filter(user=request.user)
    else:
        project_list = Project.objects.all()
    return render(request, 'budget/project-list.html', {'project_list':project_list})

def project_detail(request, project_slug):
    project = get_object_or_404(Project, slug=project_slug)

    if request.method == 'GET':
        category_list = Category.objects.filter(project=project)
        return render(request, 'budget/project-detail.html', {'project': project, 'expense_list': project.expenses.all(), 'category_list': category_list})
    elif request.method == 'POST':
        #process the form
        form = ExpenseForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            amount = form.cleaned_data['amount']
            category_name = form.cleaned_data['category']

            category = get_object_or_404(Category, project=project, name=category_name)

            Expense.objects.create(
                project=project,
                title=title,
                amount=amount,
                category=category
            ).save()

    elif request.method == 'DELETE':
        id = json.loads(request.body)['id']
        expense = get_object_or_404(Expense, id=id)
        expense.delete()

        return HttpResponse('')

    return HttpResponseRedirect(project_slug)


class ProjectCreateView(CreateView):
    model = Project
    template_name = 'budget/add-project.html'
    fields = ('name', 'budget')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()

        categories = self.request.POST['categoriesString'].split(',')
        for category in categories:
            Category.objects.create(
                project=Project.objects.get(id=self.object.id),
                name=category
            ).save()

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return slugify(self.request.POST['name'])

budgetproject/budgetproject/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created! Sign in with your new username: { username }.')
            return redirect('login')

    else:
        form = UserCreationForm()

    return render(request, 'users/register.html', {'form': form})

budgetproject/budgetproject/budget/templates/budget/add-project.html
{% extends 'budget/base.html' %}
{% load static %}

{% block title %} | New Project{% endblock %}
{%block page%}New Project{% endblock %}

{% block content %}

<!-- SECTION for TOTAL BUDGET/TOTAL TRANS/REMAINING -->
<div class="txt-body flex bg-white" style="margin-top: 5vh; margin-bottom: 0px; padding-bottom: 10vh; padding-top: 10vh;">
    <div class="container text-dark padding-horiz-10-v">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="form-group col">
                        <label for="id_name">Enter Project Name</label>
                        <input type="text" name="name" required="" id="id_name" class="form-control" placeholder="Project Name">
                    </div>

                <div class=" form-group col">
                    <label for="id_budget">Enter Project Budget</label>
                    <input type="number" name="budget" step="0.01" required="" id="id_budget" class="form-control" placeholder="Budget Amount">
                </div>
            </div>

            <div class="form-group">
                <label for="categoryInput">Expense Categories</label> 
                <input type="text" name="categoryInput" class="form-control" id="categoryInput" placeholder="Input a Category">
                <small>Please press "Enter" after each category.</small>
                <input type="hidden" name="categoriesString">

                        <ul class="justify-content-start row" style="margin: 0 3px 0 3px;" id="categoriesContainer">
                        <!-- Javascript for adding and displaying the categories -->
                    </ul>
    

            <center>
                    <a href="{% url 'list' %}" class="btn btn-outline-p" style="width: 15vw; margin-top: 20px;"> <i class="fas fa-long-arrow-alt-left"></i> Back to Dashboard</a>&ThickSpace;
                    <button type="submit" class="btn btn-p" style="width: 15vw; margin-top: 20px;"> <i class="fas fa-plus-square"></i>&ThickSpace; Start Project</button>
            </center>
        </form>
        <script src="{% static 'js/script.js' %}"></script>

        {% endblock %}
    </div>
</div>

budgetproject/budgetproject/budget/templates/budget/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>budgetBuddy{% block title %}{% endblock %}</title>
  <!-- Bootstrap Import -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
    crossorigin="anonymous">

  <!-- Imports -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <nav class="navbar fixed-top" id="global-nav">
    <a class="navbar-brand text-white" href="{% url 'list' %}">
      <img src="" width="30" height="30" class="d-inline-block align-top" alt="">
      budget<b>Buddy</b>
    </a>
    <ul class="nav justify-content-end navbar-dark">

      {% if user.is_authenticated %}




      <li class="nav-item">
        <a href="{% url 'list' %}" class="nav-link" style="color:white;">{{ user.username }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'logout' %}">Log Out</a>
      </li>

      {% else %}
      <li class="nav-item">
        <a class="btn text-white" href="{% url 'login' %}" role="button">Login</a>
      </li>
      <li class="nav-item">
        <a class="btn text-white" href="{% url 'register' %}" role="button">Sign Up</a>
      </li>
      {% endif %}
    </ul>
  </nav>

  {% if user.is_authenticated%}
  <!-- SECTION for USER INFORMATION -->
  <div class="container dashboard-display">
      <div class="row container">
          <div class="col-sm-2 align-self-center"><a href="{% url 'list' %}"
              <center><img src="https://gix.uw.edu/wp-content/uploads/2019/01/photo-placeholder-480x480.jpeg" class="user"></center></a>
          </div>
          <div class="col align-self-center">
              <h2 class="">{{user.username}}</h2>
              <h4 class="display-4">{% block page %}{% endblock %}</h4>
          </div>
      </div>

  </div>

{% else %}

  {%endif%}
  <!-- {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tag }} center">
    {{ message }}
  </div>
  {% endfor %}
  {% endif %} -->

  {% block content %}

  {% endblock %}

  </div>
</div>

<footer class="container padding-top-5-v padding-horiz-5-v">
  <div class="row">
      <div class="col padding-horiz-5-v">
      
          <address>
            <strong>budgetBuddy</strong><br>
            123 Fake Street
            <br>
            Fullerton, California
            <br>
            (123) 456 - 456
            </address>
  
          </div>
    <div class="col">
      <h5 stlye="font-weight-light">
        Contact Us
      </h5>
            Report a Bug
            <br>View Known Bugs
            <br>Feedback
    </div>
    <div class="col">
      <h5 stlye="display-4">
        About Us
      </h5>
      How to Use
      <br>Company
      <br>FAQ
      </div>

  </div>
  <center><small class="text-muted">Copyright 2019 budgetBuddy</small></center>
</footer>

  <!-- JavaScript Imports for Bootstrap -->

  <script>
  $(document).ready(function(){
    var scrollTop = 0;
    $(window).scroll(function(){
      scrollTop = $(window).scrollTop();
       $('.counter').html(scrollTop);
      
      if (scrollTop >= 100) {
        $('#global-nav').addClass('scrolled-nav');
      } else if (scrollTop < 100) {
        $('#global-nav').removeClass('scrolled-nav');
      } 
   
    }); 
    
  });</script>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

</body>

</html>

budgetproject/budgetproject/budget/templates/budget/project-detail.html
{% extends 'budget/base.html' %}
{% block title %} | Viewing Project {% endblock %}
{%block page%}{{project.name}}{% endblock %}
{% block content %}
{% load humanize %}

<!-- SECTION for TOTAL BUDGET/TOTAL TRANS/REMAINING -->
<div class="container txt-body padding-vert-5-v">

    <div class="row">
        <div class="col margin-all-1-v">
            <!-- Start of Total Budget -->
            <div class="card margin-all-1-v">
                <div class="card-body">
                    <center>
                        <h4 class="display-4">${{ project.budget|intcomma }}</h4>
                        <p>Total Budget</p>
                    </center>
                </div>
            </div>
        </div> <!-- End of Total Budget -->

        <div class="col margin-all-1-v">
            <!-- Start of Total Transactions -->
            <div class="card margin-all-1-v">
                <div class="card-body">
                    <center>
                        <h4 class="display-4">{{ project.total_transactions }}</h4>
                        <p>Total Transactions</p>
                    </center>
                </div>
            </div>
        </div> <!-- End of Total Transactions -->

        <div class="col margin-all-1-v">
            <!-- Start of Remaining Budget -->
            <div class="card margin-all-1-v">
                <div class="card-body">
                    <center>
                        {% if project.budget_percentage < 45 %} <h4 class="display-4 txt-success">${{project.budget_left}}</h4>
                            {% elif project.budget_percentage < 75 %} <h4 class="display-4 txt-warning">${{project.budget_left|intcomma}}</h4>
                                {% elif project.budget_percentage < 100 %} <h4 class="display-4 txt-danger">${{project.budget_left|intcomma }}</h4>
                                    {% else %}
                                    <h4 class="display-4 txt-overbudget">${{ project.budget_left|intcomma }}</h4>
                                    {% endif%}
                                    <p>Budget Remaining</p>
                    </center>
                </div>
            </div>
        </div> <!-- End of Remaining Budget -->
    </div>
</div>


<!-- SECTION for EXPENSES -->
<div class="txt-body bg-white padding-vert-5-v">



    <div class="container" style="padding: 15px; margin-bottom: 5px;">
        {% if project.budget_percentage > 100 %}
        <div class="alert alert-warning" role="alert">
            <center>
                <b>You're over budget!</b> Please review your budget and make adjustments where needed.</center>
        </div>
        {% endif %}

        <div class="card" style="margin-top: 5px; margin-bottom: 5px;">
            <div class="card-body" style="padding-top: 5px; padding-bottom: 5px; margin-right: 5px;">
                <div class="row">
                    <div class="col-sm-3 align-self-center txt-d-blue"><b>Expense Name</b></div>
                    <div class="col-sm-4 align-self-center txt-l-blue">
                        <center><b>Amount Spent</b></center>
                    </div>
                    <div class="col-sm-3 align-self-center txt-l-blue" style="justify-content: right;"><b>Category</b></div>
                    <div class="col-sm-2 align-self-center justify-content-end">
                        <center>
                            <button type="button" class="btn btn-b" href="#expenseModal" data-toggle="modal"><i class="fas fa-plus-square"></i>&ThickSpace;
                                Add Expense</button></center>
                    </div>
                </div>
            </div>

            <ul>
                {% for expense in expense_list %}
                <!-- displaying expenses using a for loop -->
                <li>
                    <div class="card">
                        <div class="card-body" style="margin-top: 3px; padding-top: 10px; padding-bottom: 5px; margin-right: 5px;">
                            <div class="row">
                                <div class="col-sm-3 align-self-center txt-body"><b>{{ expense.title }}</b></div>
                                <div class="col-sm-4 align-self-center">
                                    <center>${{ expense.amount|intcomma }}</center>
                                </div>
                                <div class="col-sm-4 align-self-center ">
                                    <center>{{ expense.category.name }}<center>
                                </div>
                                <div class="col-sm-1 align-self-center justify-content-end">
                                    <a onclick="deleteExpense(this)" data-id="{{ expense.id }}">
                                        <i class="material-icons btn-close" style="cursor: auto;">delete_forever</i></a>
                                </div>

                            </div>
                        </div>
                    </div>
                </li>

                {% empty %}
                <div class="txt-body bg-white padding-vert-15-v">
                    <center>
                        <h1 class="display-4 display-alert"> No transactions available</h1>

                        <p>
                            <small>Need help getting started? <a href="#">Learn more!</a></small>
                        </p>
                    </center>
                </div>

                {% endfor %}
            </ul>
        </div>
    </div>



    <!-- MODAL FOR ADD EXPENSE -->
    <div class="modal fade" id="expenseModal" tabindex="-1" role="dialog" aria-labelledby="expenseModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Adding to {{project.name}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% if project.budget_percentage > 100 %}
                    <div class="alert alert-danger" role="alert">
                        <center>
                            <b style="color: crimson;">You are currently over your budget!</b><br><small>Why am I
                                seeing this? <a href="">Learn
                                    more</a></small></center>
                    </div>
                    {% endif %}
                    <form method="POST">
                        {% csrf_token %}
                        <label for="title">Expense</label>
                        <input name="title" class="form-control" id="title" placeholder="Enter Expense Name">

                        <label for="amount">Amount</label>
                        <input name="amount" class="form-control" id="amount" placeholder="Enter Amount">

                        <label for="category">Category</label>
                        <select name="category" class="form-control">
                            {% for category in category_list %}
                            <option>{{ category.name }}</option>
                            {% endfor %}
                        </select>
                        <center>                        <button type="submit" class="btn btn-p btn-lg-30 margin-vert-1-v">Add Expense</button>
                        </center>
                    </form>
                </div>
            </div>
        </div>

        <script>
            var elem = document.querySelector('.modal')
            var instance = M.Modal.init(elem)

            var elem = document.querySelector('select')
            var instance = M.FormSelect.init(elem)

            function deleteExpense(e) {

                let id = e.dataset.id
                e.closest('li').remove()

                fetch('', {
                    method: 'DELETE',
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    body: JSON.stringify({
                        'id': id
                    }),
                    credentials: 'same-origin',
                })
                location.reload()
            }

        </script>

        {% endblock %}

budgetproject/budgetproject/budget/templates/budget/project-list.html
<!-- Main Project Dashboard for users -->

{% extends 'budget/base.html' %}
{% block title %}
{% if user.is_authenticated%}
| Dashboard{%endif%}{% endblock %}
{%block page%}Dashboard{% endblock %}

{% block content %}
{% load humanize %}

{% if user.is_authenticated %} <!-- If the user has an account, it will display the projects they have-->


<div class="txt-body bg-white padding-vert-5-v">
 <div class="container">
    <div class="card" style="margin-top: 5px; margin-bottom: 5px; border-width: 0px;">
        <div class="card-body project-list-items">
            <div class="row">
            <div class="col-sm-4 align-self-center txt-d-blue"><b>Project Name</b></div>
            <div class="col-sm-1 d-flex align-self-center txt-l-blue" ><b><center>Starting Budget</center></b></div>
            <div class="col-sm-4 align-self-center txt-l-blue"><b><center>Progress</center></b></div>
            <div class="col-sm-1 d-flex align-self-center txt-l-blue"><b><center>Budget Remaining</center></b></div>
            <div class="col-sm-2 align-self-center justify-content-end"><center>
                <a href="add" class="btn btn-b"> <i class="fas fa-plus-square"></i>&ThickSpace; Project</a></center>
            </div>
        </div>
    </div>

    {% for project in project_list  %} <!-- displaying projects using a for loop -->

    <div class="card project-list">
        <div class="card-body project-list-items">
            <div class="row">
            <div class="col-sm-4 align-self-center txt-body"><b>{{ project.name  }}</b></div>
            <div class="col-sm-2 align-self-center">${{project.budget|intcomma}}</div>
            <div class="col-sm-3 align-self-center " style="margin: 10px;">
                    <div class="progress">
                            {% if project.budget_percentage < 45 %}
                            <div class="progress-bar progress-bar-striped bg-success" style="width: {{project.budget_percentage}}%;" role="progressbar" aria-valuenow="{{project.budget_percentage}}" aria-valuemin="0" aria-valuemax="100"></div>
                            {% elif project.budget_percentage < 75 %}
                            <div class="progress-bar progress-bar-striped bg-warning " style="width: {{project.budget_percentage}}%; " role="progressbar" aria-valuenow="{{project.budget_percentage}}" aria-valuemin="0" aria-valuemax="100"></div>
                            {% else %}
                            <div class="progress-bar progress-bar-striped bg-danger" style="width: {{project.budget_percentage}}%; " role="progressbar" aria-valuenow="{{project.budget_percentage}}" aria-valuemin="0" aria-valuemax="100"></div>
                            {% endif %}
                    </div>
            </div>
            <div class="col align-self-center" style="margin: 0 25px 0 25px;">${{project.budget_left|intcomma}}</div>
            <div class="col align-self-center justify-content-end" style="margin-right: 20px;">      
                <a href="{% url 'detail' project.slug %}">View</a>
            </div>

            </div>
        </div>
    </div>

        {% empty %} <!-- If the user doesn't have projects -->

            <div class="txt-body bg-white padding-vert-15-v">
            <center>
                    <h1 class="display-4 display-alert">No projects currently saved</h1>
                    <p>
                    <small>Need help getting started? <a href="#">Learn more!</a></small>
                    </p>
                </center>
            </div>

    {% endfor %}
    </div>
                        

</div>




   

{% else %}

            <div class="welcome-display">
                <center>
                    <h1 class="display-3 text-white ">Welcome to Budget Buddy</h1>
                    <p class=""><em>Because everything is better when you do it with a friend</em></p>
                </center>
            </div>

<div class="bg-white">
        <div class="container bg-white text-dark padding-vert-5-v">
            <center>
              
                    <div class="container padding-vert-5-v"><center>
                            <div class="row justify-content-md-center">
                
                                <div class="col col-lg-2">
                                        <i class="material-icons md-48">email</i><br>
                                        <b>Signup</b>
                                        <br> 
                                        Signup with your email.
                                </div>
                                <div class="col col-lg-2">
                                        <i class="fas fa-file-contract"></i><br>
                                        <b>Create</b><br>
                                        Create budgeting projects.
                                </div>
                                <div class="col col-lg-2">
                                        <i class="fas fa-tasks"></i><br>
                                        <b>Categorize</b>
                                        <br> 
                                        Create categories to better track your expenses.
                                </div>
                                <div class="col col-lg-2">
                                        <i class="fas fa-chart-line"></i><br>
                                        <b>Track</b>
                                        <br> 
                                        Track your expenses, assist your knowledge.
                                </div>
                                <div class="col col-lg-2">
                                        <i class="fas fa-wallet"></i><br>
                                        <b>Spend</b><br>
                                        Spend wisely.
                                </div>
                            </div>
                        </center>
                        </div>
    
                  <a class="btn btn-lg btn-outline-blue btn-block" style="width: 25vw;" href="{% url 'register' %}" role="button">Register</a>
                
                </center>
                
        </div>
</div>


{% endif %}

{% endblock  %}

budgetproject/budgetproject/users/templates/users/login.html
{% extends 'budget/base.html' %}
{% block content %}
<div class="heading-display">
        <h3 class="display-3">
            <center>Login</h3></center>
                <br>
                <center><em>Please fill out the forms below to sign into your account.</em></center>
            
        
</div>
    <div class="text-dark bg-white padding-vert-5-v">
        <div class="margin-horiz-20-v">
                <form method="POST" class="margin-horiz-20-v">
                        {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_username">Username</label>
                                    <input class="form-control" type="text" name="username" autofocus="" required="" id="id_username" placeholder="Enter username">
                                </div>
            
                                <div class="form-group">
                                    <label for="id_password">Password</label>
                                    <input class="form-control" type="password" name="password" autofocus="" required="" id="id_password" placeholder="Enter Password">
                                </div>
                        <div class="form-group"><center>
                            <button type="submit" class="btn btn-lg-20 btn-b">Login</button> </center>
                        </div>
                        <small class="text-muted"><center>
                                Need an Account? <a href="{% url 'register' %}" class="ml-2">Sign Up Now</a>
                            </center>
                            </small>
                       
                    </form>

        </div>

    </div>

</center>

{% endblock %}

budgetproject/budgetproject/users/templates/users/logout.html
{% extends 'budget/base.html' %}
{% block content %}
<div class="margin-top-20-v container rounded text-dark">
        <div class="jumbotron rounded jumbotron-fluid">
                <div class="container">
                  <h1 class="display-4">Goodbye!</h1>
                  <p class="lead">You have successfully logged out</p>
                </div>
              </div>
</div>
{% endblock %}